---
ansible_host: "pve-s1.{{ inv_all_root_root_domain }}"
# ansible_host: "10.3.0.11"
fqdn: "pve-s1.{{ inv_all_root_root_domain }}"
ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
ansible_become_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
