---
- name: Test Connection
  hosts: ['pve']
  become: true
  gather_facts: true

  tasks:

    - name: Ping
      ansible.builtin.ping:

    - name: "Show hostname"
      ansible.builtin.debug:
        msg: "{{ ansible_facts.hostname }}"

    - name: Show controller IP used in SSH connection
      ansible.builtin.debug:
        msg: "Ansible connects from IP: {{ ansible_facts.default_ipv4.address }}"
